version: '3.9'

services:
  #app:
  #  # name of current services, builded by make
  #  image: apiserver
  #  ports:
  #    - "3001:3001"
  #  environment:
  #    DATABASE_URL: "postgres://db_user:db_pass@db/db_name?sslmode=disable"
  #  depends_on:
  #    db:
  #      condition: service_healthy
  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
       - db-data:/var/lib/postgresql
       - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: db_user
      POSTGRES_DB:  db_name
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db_name -U db_user"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-data: