name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install linter
      run: make install_linter

    - name: Get go deps
      run: make get_deps

    - name: Run linter
      run: make lint

    #- name: Test code
    #  run: make test

    #- name: Tests coverage
    #  run: make cover

    - name: Build binary and docker image
      id: build-image
      run: |
        make build
        make docker_image

    - name: Testing integration
      run: |
        apt install httpie
        make docker_compose_start
        make docker_compose_run_tests
        make docker_compose_stop
